### ISSUE TITLE
Docker compose runs into access denied

### ISSUE THREAD

**Issue by Zearath** [Source-Alchemists/AyBorg#58]
While using the provided ready to use Docker compose setup and running "docker compose up" from the repository root directory an error occurs:
![grafik](https://github.com/Source-Alchemists/AyBorg/assets/39257376/6e587f2c-754a-4614-ac26-974f964c4e13)

**Comment by Zearath** [comment]
The solution for me was the give the "docker-user" on the AyBorg folder full access.

**Comment by Light4Code** [comment]
Is this issue only Windows related?
Would be great if you could provide a step for step solution for other users facing this issue.

**Comment by Zearath** [comment]
So far only Windows related because I testet it only on Windows.

Sure I can do that :)
1. Right click on the AyBorg folder and click "Properties".
2. Go on the tab "Security"
3. Click on "Edit"
4. If the "docker-users" is already listed just click on this user and grant full access.
If no listed yet just click on "Add" -> "Extended" -> "Search now" -> Choose the "docker-users" -> OK -> OK -> Click on the user and grant full access.
5. Rerun the command "docker compose up" and happy using the AyBorg :)
